### ISSUE TITLE
Chore: 프로젝트 초기 설정 / Docker로 서버 배포

### ISSUE THREAD

**Issue by ParkJh38** [Capstone-Team04-AutoScheduler/BE-AutoScheduler#1]
## 📝 IssueName
> 프로젝트 초기 설정

## 📝 Description
> 프로젝트 파일 디렉토리 설정 및 ApiResponse 설정 / Docker 환경 설정
## 📝 Todo
- [x] 프로젝트 파일 디렉토리 설정
- [x] ApiResponse 설정
- [x] Docker 이미지 생성을 위한 DockerFile 생성
- [x] DockerHub와의 연동 및 Docker 컨테이너 생성 후 jar 파일 배포
- [x] EC2에 백엔드 서버 배포 후 swagger 배포

**Comment by ParkJh38** [comment]
24.10.07 Docker 이미지 -> 컨테이너 생성 후 aws EC2에 백엔드 서버 배포 및 swagger API 배포 완료하였습니다.
