### ISSUE TITLE
Feat: 일정 생성기로 부터 자동 생성된 일정 전체 개별 저장하기

### ISSUE THREAD

**Issue by ParkJh38** [Capstone-Team04-AutoScheduler/BE-AutoScheduler#90]
## 📝 IssueName
> 일정 생성기로 부터 자동 생성된 일정 전체 개별 저장하기

## 📝 Description
> 자동 생성된 여러개의 일정 분류하여 저장하기

## 📝 Todo
- [x] 자동 생성된 일정 리스트에서 개별 일정 추출하기
- [x] 개별 일정 저장하기
- [x] 일정 생성기 엔티티 수정
- [x] 일정 생성기 저장시 frames, mapping 배열, web URL 저장하도록 수정
